# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class ReposList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReposList(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReposList()
        x.Init(buf, n + offset)
        return x

    # ReposList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReposList
    def Repos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .message import message
            obj = message()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReposList
    def ReposLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ReposListStart(builder): builder.StartObject(1)
def ReposListAddRepos(builder, repos): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(repos), 0)
def ReposListStartReposVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ReposListEnd(builder): return builder.EndObject()
